config/routes.rb
Stuffchecker::Application.routes.draw do
  resources :checkers

  root :to => 'checkers#index'

end

app/models/checker.rb
class Checker < ActiveRecord::Base
  attr_accessible :codigo_rastreio, :data_chegada, :data_envio, :nome, :status_id, :status, :preco
  belongs_to :status

  before_save :save_data_chegada

  def save_data_chegada
    if self.status.valor != "Entregue"
      self.data_chegada = nil
    else
      self.data_chegada = Time.now unless !self.data_chegada.nil?
    end
  end
  

end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :valor, :id
  has_many :checkers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/checkers_controller.rb
class CheckersController < ApplicationController
  # GET /checkers
  # GET /checkers.json
  def index
    @checkers = Checker.find(:all, :order => :data_envio)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checkers }
    end
  end

  # GET /checkers/1
  # GET /checkers/1.json
  def show
    @checker = Checker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checker }
    end
  end

  # GET /checkers/new
  # GET /checkers/new.json
  def new
    @checker = Checker.new
    @status = Status.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checker }
    end
  end

  # GET /checkers/1/edit
  def edit
    @checker = Checker.find(params[:id])
  end

  # POST /checkers
  # POST /checkers.json
  def create
    
    @checker = Checker.new(params[:checker])

    respond_to do |format|
      if @checker.save
        format.html { redirect_to @checker, notice: 'Checker was successfully created.' }
        format.json { render json: @checker, status: :created, location: @checker }
      else
        format.html { render action: "new" }
        format.json { render json: @checker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checkers/1
  # PUT /checkers/1.json
  def update
    @checker = Checker.find(params[:id])
    


    respond_to do |format|
      if @checker.update_attributes(params[:checker])

        format.html { redirect_to @checker, notice: 'Checker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkers/1
  # DELETE /checkers/1.json
  def destroy
    @checker = Checker.find(params[:id])
    @checker.destroy

    respond_to do |format|
      format.html { redirect_to checkers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkers_helper.rb
module CheckersHelper
end

app/views/checkers/_form.html.erb
<%= form_for(@checker) do |f| %>
  <% if @checker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checker.errors.count, "error") %> prohibited this checker from being saved:</h2>

      <ul>
      <% @checker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :data_envio %><br />
    <%= f.date_select :data_envio, :order => [:day, :month, :year] %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br />
    <%= f.select :status_id, Status.all.collect {|p| [ p.valor, p.id ] } %>
  </div>
  <div class="field">
    <%= f.label :codigo_rastreio %><br />
    <%= f.text_field :codigo_rastreio %>
  </div>

  <div class="field">
    <%= f.label :preco %><br />
    <%= f.text_field :preco %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkers/edit.html.erb
<h1>Editing checker</h1>

<%= render 'form' %>

<%= link_to 'Show', @checker %> |
<%= link_to 'Back', checkers_path %>

app/views/checkers/index.html.erb
<h1>Produtos a Receber</h1>

<table id = 'mytable'>
  <tr>
    <th class = 'begin'>Data envio</th>    
    <th>Preço</th> 
    <th>Nome</th>
    <th>Status</th>
    <th>Codigo rastreio</th>
    <th>Dias desde Envio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checkers.each do |checker| %>
  <% if checker.status.valor != "Entregue" %>
    <tr>
      <td class = 'begin'><%= checker.data_envio.strftime("%d/%m/%y") %></td>
      <td><%= checker.preco %></td>
      <td><%= checker.nome %></td>
      <td><%= checker.status.valor %></td>
      <td><%= link_to checker.codigo_rastreio, "http://websro.correios.com.br/sro_bin/txect01$.QueryList?P_LINGUA=001&P_TIPO=001&P_COD_UNI=" + checker.codigo_rastreio %></td>     
      <td><%= time_ago_in_words(checker.data_envio) %> </td>
      <td><%= link_to 'Show', checker %></td>
      <td><%= link_to 'Edit', edit_checker_path(checker) %></td>
      <td><%= link_to 'Destroy', checker, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end -%>
<% end %>
</table>

<br />


<h1>Produtos Recebidos</h1>

<table id = 'mytable'>
  <tr>
    <th class = 'begin'>Data envio</th>
    <th>Nome</th>
    <th>Status</th>
    <th>Data chegada</th>
    <th>Codigo rastreio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checkers.each do |checker| %>
  <% if checker.status.valor == "Entregue" %>
    <tr>
      <td class = 'begin'><%= checker.data_envio.strftime("%d/%m/%y") %></td>
      <td><%= checker.nome %></td>
      <td><%= checker.status.valor %></td>
      <td><%= checker.data_chegada.strftime("%d/%m/%y") unless checker.data_chegada.nil?%></td>
      <td><%= link_to checker.codigo_rastreio, "http://websro.correios.com.br/sro_bin/txect01$.QueryList?P_LINGUA=001&P_TIPO=001&P_COD_UNI=" + checker.codigo_rastreio %></td>
      <td><%= link_to 'Show', checker %></td>
      <td><%= link_to 'Edit', edit_checker_path(checker) %></td>
      <td><%= link_to 'Destroy', checker, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end -%>
<% end %>
</table>

<br />
<%= link_to 'New Checker', new_checker_path %>

app/views/checkers/new.html.erb
<h1>New checker</h1>

<%= render 'form' %>

<%= link_to 'Back', checkers_path %>

app/views/checkers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @checker.nome %>
</p>

<p>
  <b>Data envio:</b>
  <%= @checker.data_envio %>
</p>

<p>
  <b>Data chegada:</b>
  <%= @checker.data_chegada %>
</p>

<p>
  <b>Codigo rastreio:</b>
  <%= @checker.codigo_rastreio %>
</p>


<%= link_to 'Edit', edit_checker_path(@checker) %> |
<%= link_to 'Back', checkers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stuffchecker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>